// backend/services/anthropicService.js

/**
 * Service Abstraction for Anthropic (Claude 3.5 Sonnet)
 * Incorporates the "Tomorrow" Constraint with a 1-second delay for MOCK testing.
 */

const isMock = !process.env.ANTHROPIC_API_KEY || process.env.ANTHROPIC_API_KEY === 'MOCK';

exports.generateReport = async (summaryText, transcriptText, templateType) => {
    if (isMock) {
        console.log(`[MOCK] Generating ${templateType} report from Anthropic...`);
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    reportContent: `<h1>${templateType.charAt(0).toUpperCase() + templateType.slice(1)} Report</h1>\n<p>This is a mock report generated by the Anthropic service abstraction layer. It combined the summary and transcript into this beautifully formatted document.</p>\n<h2>Key Findings</h2>\n<ul><li>Service abstraction allows end-to-end testing today.</li><li>Socket.IO enables real-time progress updates.</li></ul>`
                });
            }, 1000);
        });
    }

    // Production Anthropic Claude logic goes here
};
