// backend/services/openaiService.js
const fs = require('fs');
const { OpenAI } = require('openai');
const promptSettingsService = require('./promptSettingsService');

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY
});

const isMock = !process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === 'MOCK';

exports.transcribeAudio = async (filePath, language = 'en-US') => {
    if (isMock) {
        console.log(`[MOCK] Transcribing audio file: ${filePath}`);
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    text: "This is a mock transcription of the uploaded audio. The real OpenAI Whisper API will replace this text once the actual API key is provided tomorrow. We can see that the system successfully processed the file and emitted the socket events perfectly.",
                    language: "en",
                    duration: 15.5,
                    segments: [
                        { start: 0, end: 15.5, text: "This is a mock transcription of the uploaded audio..." }
                    ]
                });
            }, 1000); // 1-second mock delay
        });
    }

    try {
        console.log(`[OpenAI] Sending file ${filePath} to Whisper API...`);
        const whisperLang = language === 'ur-PK' ? 'ur' : 'en';
        const transcription = await openai.audio.transcriptions.create({
            file: fs.createReadStream(filePath),
            model: 'whisper-1',
            response_format: 'verbose_json', // Gets segments and duration
            language: whisperLang
        });

        return {
            text: transcription.text,
            language: transcription.language,
            duration: transcription.duration,
            segments: transcription.segments
        };
    } catch (error) {
        console.error('[OpenAI Whisper Error]:', error);
        throw error;
    }
};

exports.generateSummary = async (transcriptText, customPrompt = null, length = null, style = null, language = null) => {
    // 1. Throw error if empty
    if (!transcriptText || transcriptText.trim().length === 0) {
        throw new Error("No audio or transcription data is available to generate a summary.");
    }

    // 2. Format language for the prompt
    let langInstruction = "Detect the language of the transcript provided and generate the summary, tags, and queries in that same language (e.g., if the transcript is in Urdu, write the summary in Urdu). If the language is ambiguous or too short to detect accurately, DEFAULT to English.";
    if (language) {
        langInstruction = `You MUST write the summary, tags, and queries entirely in ${language}. Ignore the source language of the transcript and TRANSLATE your response into ${language} if necessary.`;
    }

    if (isMock) {
        console.log(`[MOCK] Generating summary for transcript length: ${transcriptText.length}`);
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    summary: "This executive summary was generated by the mock service. It highlights the main points discussed in the audio recording, including the successful implementation of the BullMQ worker architecture and Socket.IO real-time updates.",
                    tags: ["architecture", "real-time", "bullmq", "mock-data"],
                    queries: ["How to scale BullMQ with Redis", "Socket.IO real-time dashboard patterns"]
                });
            }, 1000); // 1-second mock delay
        });
    }

    try {
        console.log(`[OpenAI] Sending transcript to GPT for summarization...`);

        // The persona/mission sentences (summaryPrompt, queryExtractionPrompt) are
        // admin-editable (see PromptSettings/promptSettingsAdminController) - everything
        // else here is a technical contract (JSON schema, language instruction) the code
        // depends on to parse the response, so it stays hardcoded.
        const promptSettings = await promptSettingsService.getPromptSettings();

        let systemPrompt = `You are a highly skilled AI assistant that analyzes meeting transcripts and audio logs.
${promptSettings.summaryPrompt}
${promptSettings.queryExtractionPrompt}
Return your response STRICTLY as a JSON object with the following schema:
{
  "summary": "String containing the formatted summary",
  "tags": ["Array", "of", "strings", "representing", "topics"],
  "queries": ["Array", "of", "strings", "representing", "follow-up questions"]
}

CRITICAL INSTRUCTION: ${langInstruction}`;

        if (length) {
            systemPrompt += `\n\nLENGTH REQUIREMENT: Make the summary length "${length}".`;
        }
        if (style) {
            systemPrompt += `\n\nSTYLE REQUIREMENT: Format the summary as "${style}".`;
        }
        if (customPrompt) {
            systemPrompt += `\n\nUSER CUSTOM INTENT/PROMPT: The user has specifically requested you to focus on the following when summarizing: "${customPrompt}"`;
        }

        const response = await openai.chat.completions.create({
            model: 'gpt-4o-mini', // Using cost-effective model, can be upgraded to gpt-4o
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: `Transcript:\n\n${transcriptText}` }
            ],
            response_format: { type: "json_object" }
        });

        const result = JSON.parse(response.choices[0].message.content);
        return {
            summary: result.summary,
            tags: result.tags || [],
            queries: result.queries || []
        };
    } catch (error) {
        console.error('[OpenAI GPT Error]:', error);
        throw error;
    }
};

// Answers a specific "Processing Intent" prompt (e.g. "Extract Action Items") against a
// transcript, kept separate from generateSummary's JSON summary/tags/queries schema since
// this is free-form Q&A, not a formatted summary - plain text response, never persisted
// (mirrors translateText's synchronous, ephemeral pattern).
exports.answerAboutTranscript = async (transcriptText, prompt, language = null) => {
    if (!transcriptText || !transcriptText.trim()) {
        throw new Error('No transcript text is available to process yet.');
    }
    if (!prompt || !prompt.trim()) {
        throw new Error('A prompt is required.');
    }

    if (isMock) {
        console.log(`[MOCK] Answering intent prompt: ${prompt}`);
        return new Promise((resolve) => {
            setTimeout(() => resolve(`[MOCK ANSWER] Based on the transcript, here is the response to "${prompt}".`), 1000);
        });
    }

    let langInstruction = 'Detect the language of the transcript and answer in that same language. If ambiguous, default to English.';
    if (language) {
        langInstruction = `You MUST answer entirely in ${language}, regardless of the transcript's source language.`;
    }

    try {
        console.log(`[OpenAI] Answering intent prompt against transcript...`);
        const response = await openai.chat.completions.create({
            model: 'gpt-4o-mini',
            messages: [
                {
                    role: 'system',
                    content: `You are a highly skilled AI assistant analyzing a meeting/audio transcript. The user will give you a specific instruction or question - respond to it directly and concisely, using only information present in the transcript. If the transcript doesn't contain enough information to answer, say so plainly. ${langInstruction} Return plain text only - no JSON, no markdown code fences.`
                },
                { role: 'user', content: `Transcript:\n\n${transcriptText}\n\nInstruction/Question:\n${prompt}` }
            ]
        });
        return response.choices[0].message.content.trim();
    } catch (error) {
        console.error('[OpenAI Intent Answer Error]:', error);
        throw error;
    }
};

const SUPPORT_SYSTEM_PROMPT = `You are the ThinkMic 24/7 AI support assistant. ThinkMic is an AI-driven audio intelligence and research platform. Its features: live audio recording and file-upload transcription (English and Urdu), AI-generated summaries and reports (PDF/DOCX, multiple templates), web research tied to a recording session, a coin wallet with referral rewards, seminars (live seminars with attendee registration, plus a "Nearby Seminars" map), a Schema Builder / Collaboration area for custom data-collection forms, and account Settings (profile, identity/KYC, notifications, security).

Answer the user's support question helpfully and concisely (2-4 sentences) using only what's listed above. If it's something you cannot know from this context (their specific account data, an exact coin balance, order status, a bug only staff can investigate), say so plainly and let them know a human team member will follow up - do not invent account-specific facts. Be warm but brief. Return plain text only, no markdown formatting.`;

// A real human staff member can jump into any ticket at any time (see supportController.js
// - isStaff messages don't stop this from firing again on the *next* user message unless
// staff has already replied at least once in the ticket).
exports.answerSupportQuestion = async (conversationText, category) => {
    if (isMock) {
        console.log(`[MOCK] Answering support question for category: ${category}`);
        return new Promise((resolve) => {
            setTimeout(() => resolve(`[MOCK AI SUPPORT REPLY] Thanks for reaching out about "${category || 'General'}" - a real answer would appear here once OPENAI_API_KEY is configured.`), 800);
        });
    }

    try {
        const response = await openai.chat.completions.create({
            model: 'gpt-4o-mini',
            messages: [
                { role: 'system', content: SUPPORT_SYSTEM_PROMPT },
                { role: 'user', content: `Support category: ${category || 'General'}\n\nConversation so far:\n${conversationText}\n\nWrite the next reply from the assistant.` }
            ]
        });
        return response.choices[0].message.content.trim();
    } catch (error) {
        console.error('[OpenAI Support Answer Error]:', error);
        throw error;
    }
};

exports.translateText = async (text, targetLanguageName) => {
    if (!text || !text.trim()) {
        throw new Error('No text provided to translate.');
    }

    if (isMock) {
        console.log(`[MOCK] Translating text to ${targetLanguageName}`);
        return new Promise((resolve) => {
            setTimeout(() => resolve(`[${targetLanguageName} MOCK TRANSLATION] ${text}`), 500);
        });
    }

    try {
        console.log(`[OpenAI] Translating text to ${targetLanguageName}...`);
        const response = await openai.chat.completions.create({
            model: 'gpt-4o-mini',
            messages: [
                {
                    role: 'system',
                    content: `You are a professional translator. Translate the user's text into ${targetLanguageName}, preserving the original meaning, tone, and paragraph structure as closely as possible. Return ONLY the translated text - no preamble, quotes, or commentary.`
                },
                { role: 'user', content: text }
            ]
        });
        return response.choices[0].message.content.trim();
    } catch (error) {
        console.error('[OpenAI Translate Error]:', error);
        throw error;
    }
};

// Section structure per template - each maps to the report's `template` enum on Report.js
const REPORT_TEMPLATE_STRUCTURES = {
    academic: `- Abstract / Executive Summary (<h2>Abstract</h2>)
- Methodology & Context (<h2>Methodology & Context</h2>)
- Literature & Web Synthesis (<h2>Literature & Web Synthesis</h2>) - synthesize the web research into a scholarly narrative, citing sources inline with <a href="...">
- Direct Quotations & Evidence (<h2>Direct Quotations & Evidence</h2>) - use <blockquote> for verbatim transcript quotes or notable research excerpts
- Structured References (<h2>References</h2>) - a <table> of cited sources with their URLs`,
    executive: `- Executive Brief (<h2>Executive Brief</h2>) - a tight, high-level overview for decision-makers
- Key Insights & Drivers (<h2>Key Insights & Drivers</h2>)
- Strategic Recommendations (<h2>Strategic Recommendations</h2>)
- Risk & Opportunity Matrix (<h2>Risk & Opportunity Matrix</h2>) - a <table> with columns for Item, Type (Risk/Opportunity), and Impact
- Cited Sources (<h2>Cited Sources</h2>)`,
    standard: `- Overview (<h2>Overview</h2>)
- Detailed Analysis (<h2>Detailed Analysis</h2>)
- Key Data Points & Bulletins (<h2>Key Data Points</h2>) - <ul><li> bullet points
- Speech Transcripts (<h2>Speech Transcripts</h2>) - use <blockquote> for quoted excerpts
- Web References (<h2>Web References</h2>)`
};

exports.generateReport = async (summaryText, transcriptText, templateType, sections = {}, language = null) => {
    try {
        const normalizedTemplate = REPORT_TEMPLATE_STRUCTURES[templateType] ? templateType : 'standard';
        console.log(`[OpenAI] Generating ${normalizedTemplate} report...`);

        // reportPrompt (the persona/mission sentence) is admin-editable (see PromptSettings/
        // promptSettingsAdminController) - the output-format contract below it stays
        // hardcoded since the PDF/DOCX renderer depends on it being real semantic HTML.
        const promptSettings = await promptSettingsService.getPromptSettings();

        let systemPrompt = `${promptSettings.reportPrompt}

Return ONLY raw semantic HTML suitable for injecting directly into a <div> - never markdown, never JSON, and never \`\`\` code fences.
Use only these tags: <h1>, <h2>, <h3>, <p>, <ul>, <li>, <blockquote>, <table>, <tr>, <td>, <th>, <a>, <strong>, <em>.
Use <blockquote> for direct quotes from the transcript or research, and <a href="..."> for every cited web source URL.
If the source material contains Urdu or any other non-English script, preserve it verbatim in its original language and script - do not transliterate or translate it.
If the report includes a transcript section, the complete verbatim transcript is appended automatically as its own appendix after your content - do not attempt to reproduce the full transcript yourself, just quote the handful of most relevant excerpts.`;

        if (language) {
            systemPrompt += `\n\nCRITICAL LANGUAGE INSTRUCTION: Write the entire report (all headings, analysis, and commentary) in ${language}, regardless of the source material's language. Direct quotations from the transcript may stay in their original spoken language for authenticity, but everything else must be in ${language}.`;
        }

        systemPrompt += `\n\nStructure the report using this "${normalizedTemplate}" template:
${REPORT_TEMPLATE_STRUCTURES[normalizedTemplate]}`;

        let requestedSections = [];
        if (sections.summary) requestedSections.push("Executive/Abstract Summary");
        if (sections.research) requestedSections.push("Web Research Synthesis");
        if (sections.transcript) requestedSections.push("Audio Transcript Quotes");
        if (sections.sources) requestedSections.push("Sources & Citations");

        let userContent = `SUMMARY MATERIAL:\n${summaryText || '(none provided)'}\n\nRESEARCH & TRANSCRIPT MATERIAL:\n${transcriptText || '(none provided)'}\n\n`;
        if (requestedSections.length > 0) {
            userContent += `Only include the following sections, in this order, and OMIT any section whose source material is unavailable above: ${requestedSections.join(', ')}.`;
        } else {
            userContent += `No specific sections were requested - use your judgement to produce a complete report following the template structure above, omitting sections with no available source material.`;
        }

        const response = await openai.chat.completions.create({
            model: 'gpt-4o',
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: userContent }
            ]
        });

        let content = response.choices[0].message.content;
        // Strip markdown backticks if OpenAI mistakenly includes them
        content = content.replace(/^```html/, '').replace(/^```/, '').replace(/```$/, '').trim();
        return { reportContent: content };
    } catch (error) {
        console.error('[OpenAI Report Error]:', error);
        throw error;
    }
};

exports.generateNoteInsights = async (noteContent) => {
    if (!noteContent || noteContent.trim().length === 0) {
        throw new Error("Note content is empty.");
    }

    if (isMock) {
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    outline: ["Introduction", "Main Key Points", "Action Items", "Conclusion"],
                    tags: ["AI", "Insights", "Productivity"]
                });
            }, 1000);
        });
    }

    try {
        console.log(`[OpenAI] Generating insights for note...`);
        let systemPrompt = `You are a highly skilled AI assistant that analyzes meeting notes and documents.
Your job is to provide a brief logical outline and extract key topics/tags for the given note content.
Return your response STRICTLY as a JSON object with the following schema:
{
  "outline": ["Array", "of", "strings", "representing", "the outline or structure of the document"],
  "tags": ["Array", "of", "strings", "representing", "short tags/topics"]
}
Keep the outline concise (3-5 items maximum, representing the high-level sections). Keep the tags concise (3-6 tags). If the note is very short, adapt accordingly.`;

        const response = await openai.chat.completions.create({
            model: 'gpt-4o-mini',
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: `Note Content:\n\n${noteContent}` }
            ],
            response_format: { type: "json_object" }
        });

        const result = JSON.parse(response.choices[0].message.content);
        return {
            outline: result.outline || [],
            tags: result.tags || []
        };
    } catch (error) {
        console.error('[OpenAI Note Insights Error]:', error);
        throw error;
    }
};
