// backend/services/openaiService.js
const fs = require('fs');

/**
 * Service Abstraction for OpenAI (Whisper & GPT-4o)
 * Incorporates the "Tomorrow" Constraint with a 1-second delay for MOCK testing.
 */

const isMock = !process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === 'MOCK';

exports.transcribeAudio = async (filePath) => {
    if (isMock) {
        console.log(`[MOCK] Transcribing audio file: ${filePath}`);
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    text: "This is a mock transcription of the uploaded audio. The real OpenAI Whisper API will replace this text once the actual API key is provided tomorrow. We can see that the system successfully processed the file and emitted the socket events perfectly.",
                    language: "en",
                    duration: 15.5,
                    segments: [
                        { start: 0, end: 15.5, text: "This is a mock transcription of the uploaded audio..." }
                    ]
                });
            }, 1000); // 1-second mock delay
        });
    }

    // Production OpenAI Whisper logic goes here
    // const formData = new FormData();
    // formData.append('file', fs.createReadStream(filePath));
    // formData.append('model', 'whisper-1');
    // const response = await axios.post('https://api.openai.com/v1/audio/transcriptions', formData, { ... });
    // return response.data;
};

exports.generateSummary = async (transcriptText, customPrompt = null) => {
    if (isMock) {
        console.log(`[MOCK] Generating summary for transcript length: ${transcriptText.length}`);
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    summary: "This executive summary was generated by the mock service. It highlights the main points discussed in the audio recording, including the successful implementation of the BullMQ worker architecture and Socket.IO real-time updates.",
                    tags: ["architecture", "real-time", "bullmq", "mock-data"],
                    queries: ["How to scale BullMQ with Redis", "Socket.IO real-time dashboard patterns"]
                });
            }, 1000); // 1-second mock delay
        });
    }

    // Production GPT-4o logic goes here
};
