// backend/services/openaiService.js
const fs = require('fs');
const { OpenAI } = require('openai');

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY
});

const isMock = !process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === 'MOCK';

exports.transcribeAudio = async (filePath, language = 'en-US') => {
    if (isMock) {
        console.log(`[MOCK] Transcribing audio file: ${filePath}`);
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    text: "This is a mock transcription of the uploaded audio. The real OpenAI Whisper API will replace this text once the actual API key is provided tomorrow. We can see that the system successfully processed the file and emitted the socket events perfectly.",
                    language: "en",
                    duration: 15.5,
                    segments: [
                        { start: 0, end: 15.5, text: "This is a mock transcription of the uploaded audio..." }
                    ]
                });
            }, 1000); // 1-second mock delay
        });
    }

    try {
        console.log(`[OpenAI] Sending file ${filePath} to Whisper API...`);
        const whisperLang = language === 'ur-PK' ? 'ur' : 'en';
        const transcription = await openai.audio.transcriptions.create({
            file: fs.createReadStream(filePath),
            model: 'whisper-1',
            response_format: 'verbose_json', // Gets segments and duration
            language: whisperLang
        });

        return {
            text: transcription.text,
            language: transcription.language,
            duration: transcription.duration,
            segments: transcription.segments
        };
    } catch (error) {
        console.error('[OpenAI Whisper Error]:', error);
        throw error;
    }
};

exports.generateSummary = async (transcriptText, customPrompt = null, length = null, style = null, language = null) => {
    // 1. Throw error if empty
    if (!transcriptText || transcriptText.trim().length === 0) {
        throw new Error("No audio or transcription data is available to generate a summary.");
    }

    // 2. Format language for the prompt
    let langInstruction = "Detect the language of the transcript provided and generate the summary, tags, and queries in that same language (e.g., if the transcript is in Urdu, write the summary in Urdu). If the language is ambiguous or too short to detect accurately, DEFAULT to English.";
    if (language) {
        langInstruction = `You MUST write the summary, tags, and queries entirely in ${language}. Ignore the source language of the transcript and TRANSLATE your response into ${language} if necessary.`;
    }

    if (isMock) {
        console.log(`[MOCK] Generating summary for transcript length: ${transcriptText.length}`);
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    summary: "This executive summary was generated by the mock service. It highlights the main points discussed in the audio recording, including the successful implementation of the BullMQ worker architecture and Socket.IO real-time updates.",
                    tags: ["architecture", "real-time", "bullmq", "mock-data"],
                    queries: ["How to scale BullMQ with Redis", "Socket.IO real-time dashboard patterns"]
                });
            }, 1000); // 1-second mock delay
        });
    }

    try {
        console.log(`[OpenAI] Sending transcript to GPT for summarization...`);
        
        let systemPrompt = `You are a highly skilled AI assistant that analyzes meeting transcripts and audio logs.
Your job is to provide a comprehensive summary and extract key topics/tags and suggested follow-up questions/queries.
Return your response STRICTLY as a JSON object with the following schema:
{
  "summary": "String containing the formatted summary",
  "tags": ["Array", "of", "strings", "representing", "topics"],
  "queries": ["Array", "of", "strings", "representing", "follow-up questions"]
}

CRITICAL INSTRUCTION: ${langInstruction}`;

        if (length) {
            systemPrompt += `\n\nLENGTH REQUIREMENT: Make the summary length "${length}".`;
        }
        if (style) {
            systemPrompt += `\n\nSTYLE REQUIREMENT: Format the summary as "${style}".`;
        }
        if (customPrompt) {
            systemPrompt += `\n\nUSER CUSTOM INTENT/PROMPT: The user has specifically requested you to focus on the following when summarizing: "${customPrompt}"`;
        }

        const response = await openai.chat.completions.create({
            model: 'gpt-4o-mini', // Using cost-effective model, can be upgraded to gpt-4o
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: `Transcript:\n\n${transcriptText}` }
            ],
            response_format: { type: "json_object" }
        });

        const result = JSON.parse(response.choices[0].message.content);
        return {
            summary: result.summary,
            tags: result.tags || [],
            queries: result.queries || []
        };
    } catch (error) {
        console.error('[OpenAI GPT Error]:', error);
        throw error;
    }
};
